language: python
python:
    - '3.6'
sudo: false
cache:
    directories:
        - "$HOME/.cache/pip"
install:
    pip install flake8 -r requirements.txt
script:
    flake8 --max-line-length=250 --exclude=*/migrations/* api apps
    ./manage.py test
