language: python
python:
    - '3.6'
sudo: false
cache:
    directories:
        - "$HOME/.cache/pip"
install:
    pip install pipenv
    pipenv install --dev
script:
    pipenv run flake8
    pipenv run ./manage.py test
