language: python
python:
    - '3.6'
sudo: false
cache:
    directories:
        - "$HOME/.cache/pip"
install:
    pip install flake8 -r requirements.txt
script:
    flake8 --ignore=E501,W504 --exclude=venv,*/migrations/*,tests.py,*/commands/* api apps
    ./manage.py test
