version: 2.1
orbs:
  react-tools: pennlabs/react-tools@0.0.5

jobs:
  backend:
    working_directory: ~/pcr
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: mysql://root:password@127.0.0.1:3306/circle_test
      - image: circleci/mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: circle_test
      - image: circleci/node:10
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            pipenv install -d
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: Lint
          command: |
            pipenv run flake8
      - run:
          name: Run tests
          command: |
            pipenv run coverage run manage.py test

workflows:
  version: 2
  build:
    jobs:
      - react-tools/check:
          project-location: frontend
          image: pennlabs/frontend-test:latest
      - backend
